# Generated by Django 2.0 on 2018-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
