# Generated by Django 2.0 on 2018-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_pin',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
