# Generated by Django 2.0 on 2018-03-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_account_account_pin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='ConsumerAccount',
        ),
    ]
