# Generated by Django 2.0 on 2018-03-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0003_auto_20180327_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumerAccount',
            new_name='Account',
        ),
    ]
