# Generated by Django 2.0 on 2018-03-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0005_auto_20180329_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
