# Generated by Django 2.0 on 2018-04-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0007_auto_20180329_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True},
        ),
    ]
