# Generated by Django 2.0 on 2018-04-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0008_auto_20180405_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
